### PR TITLE
[FIX] component: error handling: rendering with sub components

### LINKED ISSUE #425: Errors occurring in render (with sub components) are sometimes never displayed
```js
const elements = [1, 2];
const state = {1: {val: 'hello'}};
```

```xml
<t t-foreach="elements" t-as="element">
   <SubComponent p="state[element].val"/>
</t>
```

When the crash occurs (on second SubComponent), the fiber counter is 1, so the fiber can't be processed, and the error is never displayed.

### PR DESCRIPTION
**Pull request by aab-odoo**
Closes #425

### CODE REVIEW

File: src/component/fiber.ts [hunk 1]
```diff
@@ -216,7 +217,9 @@ export class Fiber {
         component.catchError!(error);
       });
     } else {
+      this.root.counter = 0;
```
Comment (ged-odoo) [inline src/component/fiber.ts]: explain
