### PR TITLE
[FIX] compiler: allow t-out on component tag

### LINKED ISSUE #1483: Unexpected different behaviour for t-out and t-esc when used on a component tag
Using a t-esc on a component tag does add the text to the component default slot, while using a t-out replaces the whole component tag by a text node. I think the behaviour should be the same for both.

```xml
<Comp t-esc="'foo'"/> => <div class="my-comp">foo</div>

<Comp t-out="'foo'"/> =>  "foo"
```

### PR DESCRIPTION
**Pull request by ged-odoo**
Before this commit, the template parser would allow using t-esc on a component tag (<MyComponent t-esc="expr"/>) but would incorrectly ignore the component when parsing a t-out: <MyComponent t-out="expr"/> would be parsed as <t t-out="expr"/>

This commit solves the issue, and also, moves the `t-out` parsing code next to `t-esc` so they have the same priority relatively to other directives.

closes #1483

### CODE REVIEW

File: src/compiler/parser.ts [hunk 1]
```diff
@@ -941,21 +938,23 @@ function normalizeTIf(el: Element) {
...
-    if (el.childNodes.length) {
-      throw new OwlError("Cannot have t-esc on a component that already has content");
-    }
-    const value = el.getAttribute("t-esc");
-    el.removeAttribute("t-esc");
-    const t = el.ownerDocument.createElement("t");
-    if (value != null) {
-      t.setAttribute("t-esc", value);
+function normalizeTEscTOut(el: Element) {
+  for (let tag of ["t-esc", "t-out"]) {
```
Comment (sdegueldre) [inline src/compiler/parser.ts:942]: It's a little weird to call an attribute "tag" (also you can use const because tag is never reassignedà

**Review by sdegueldre — APPROVED** [review]
Minor comment
