### PR TITLE
[IMP] owl: add basic support for sub roots

### LINKED ISSUE #1640: app should have a way to have multiple roots
Knowledge has to create a new app for each embedded components. This is slightly annoying because there is some bookkeeping to do to copy the app configuration. Also, the sub app cannot have the same template cache, since compiled templates keep a reference to the app and doing that may cause weird crashes.

Another usecase could be website, which may have 1 single owl app with multiple roots all over the page.

I don't think that it would be very difficult to modify the App class to support multiple root nodes:
```js
app.mount(Component, root)
```

### PR DESCRIPTION
**Pull request by ged-odoo**
In this commit, we extend the owl App class to support multiple sub roots. This is useful for situations where we want to mount sub components in non-managed DOM. This is exactly what the Knowledge app is doing, with mounting views in an html editor.

Currently, this requires some difficult and fragile hacks, and still, the result is that it is very easy to mix components from the main App and a SubApp.  But Knowledge does not actually care about creating a sub app. It only needs the possibility to mount sub components in dynamic places.

closes #1640

### CODE REVIEW

File: src/runtime/app.ts [hunk 1]
```diff
@@ -101,6 +108,30 @@ export class App<
...
+    this.subRoots.add(node);
+    return {
+      root: node,
+      mount: (target: HTMLElement | ShadowRoot, options?: MountOptions) => {
+        App.validateTarget(target);
+        if (this.dev) {
+          validateProps(SubRoot, subProps, { __owl__: { app: this } });
+        }
+        const prom = this.mountNode(node, target, options);
+        return prom;
```
Comment (sdegueldre) [inline src/runtime/app.ts:125]: Shouldn't mount call createRoot?

File: src/runtime/app.ts [hunk 2]
```diff
@@ -134,6 +165,9 @@ export class App<
 
   destroy() {
     if (this.root) {
```
Comment (sdegueldre) [inline src/runtime/app.ts:167]: Will knowledge have a main root? If not then destroy will not work in this current state

**Review by aab-odoo — APPROVED** [review]

File: src/runtime/app.ts (hunk 2 above)
Comment (ged-odoo) [reply src/runtime/app.ts:178]: yes, they will have to destroy the root manually using the return object from createRoot. The code here is just for correctness.

File: src/runtime/app.ts (hunk 1 above)
Comment (ged-odoo) [reply src/runtime/app.ts]: done (but not as elegant as one might expect, i had to remove something from the subroot sets. this could probably be improved in the future in owl 3. i think the App class is not designed properly, it should basically not have a mount method, only a createRoot.

**Review by sdegueldre — APPROVED** [review]
