### PR TITLE
[FIX] portal: manually unmounting works

### LINKED ISSUE #531: Portal is not destroyed when parent is unmounted
**JavaScript :**
```js
const { Portal } = owl.misc;

class App extends owl.Component {
    static components = { Portal };
}

const app = new App();
app.mount(document.body)
    .then(() => app.unmount());
```
**XML :**
```xml
<templates>
  <div t-name="App">
    <Portal target="'body'">
      <p>I'm travelling through space!</p>
    </Portal>
  </div>
</templates>
```
**Error :**
`Portal` is not destroyed after `App` is unmounted

### PR DESCRIPTION
**Pull request by kebeclibre**
Before this commit, when manually unmounting the portal
or one of its parents, the teleported elements were not cleaned
and stayed teleported forever

After this commit, the teleported content is brought back and
unmounted much like any component

closes #531

### CODE REVIEW

File: src/misc/portal.ts [hunk 1]
```diff
@@ -59,6 +59,21 @@ export class Portal extends Component<any, any> {
...
+   */
+  __callWillUnmount() {
+    if (this.el && this.portal && this.portal.elm) {
+      this.el.appendChild(this.portal.elm);
+      const vnode = this.__owl__.vnode;
+      vnode!.children = [this.portal];
+      this.portal = null;
+      this.doTargetLookUp = true;
+    }
+    super.__callWillUnmount();
```
Comment (ged-odoo) [inline src/misc/portal.ts]: this should be done at the beginning. otherwise subcomponents will not be at the correct place when they are unmounted

**Comment by kebeclibre** [comment]
@ged-odoo 
Done !
Hooks willunmount and mounted are correctly tested

File: src/misc/portal.ts [hunk 2]
```diff
@@ -59,6 +59,18 @@ export class Portal extends Component<any, any> {
...
     });
   }
+  /**
+   * Override to revert back to a classic Component's structure
+   *
+   * @override
+   */
+  __callWillUnmount() {
+    super.__callWillUnmount();
+    if (this.el && this.portal && this.portal.elm) {
```
Comment (ged-odoo) [inline src/misc/portal.ts]: I think that if you component is being unmounted, then it necessarily has a `el`, `portal` and `portal.elm`, so you can remove this `if`
