### PR TITLE
[FIX] debug tools: do not crash on non json-stringifiable props

### LINKED ISSUE #595: debug script: cannot handle some props
if a props is non-stringifiable, it crashes.

### PR DESCRIPTION
**Pull request by ged-odoo**
closes #595

### CODE REVIEW

File: tools/debug.js [hunk 1]
```diff
@@ -35,7 +35,12 @@
   });
 
   function toStr(obj) {
-    let str = JSON.stringify(obj || {});
+    let str;
+    try {
+      str = JSON.stringify(obj || {});
+    } catch (e) {
+      str = "<...>";
```
Comment (kebeclibre) [inline tools/debug.js]: @ged-odoo 
Might be ambiguous with `...` in case the string is too long
I'd go for for something explicit e.g. `<JSON error>`

Comment (aab-odoo) [reply tools/debug.js]: I agree
