### PR TITLE
[FIX] qweb: properly handle empty class attribute

### LINKED ISSUE #530: empty class causes a crash
```js
    <div class=" ">test</div>
```

same with "" or "   "

### PR DESCRIPTION
**Pull request by ged-odoo**
The classList.add method actually crashes when given an empty string (or
a string with just white spaces).

closes #530

### CODE REVIEW

File: src/qweb/qweb.ts [hunk 1]
```diff
@@ -650,13 +650,15 @@ export class QWeb extends EventBus {
...
         const attID = ctx.generateID();
         if (name === "class") {
-          let classDef = value
-            .trim()
-            .split(/\s+/)
-            .map(a => `'${a}':true`)
-            .join(",");
-          classObj = `_${ctx.generateID()}`;
-          ctx.addLine(`let ${classObj} = {${classDef}};`);
+          if (value.trim()) {
```
Comment (aab-odoo) [inline src/qweb/qweb.ts]: maybe do `value = value.trim();` before if() to prevent from calling trim twice
